<?php

?>
<?php /** @var $this \Magento\Framework\View\TemplateEngine\Php  */ ?>
<?php /** @var $block \LimeSoda\Cashpresso\Block\Frontend\Checkout\Script  */ ?>
<?php $customer = $block->getCustomer(); ?>
<script id="c2CheckoutScript" type="text/javascript"
        src="<?php echo $block->getConfig()->getJsCheckoutScript() ?>"
        defer
        data-c2-partnerApiKey="<?php echo $block->getConfig()->getAPIKey($block->getStoreId()) ?>"
        data-c2-interestFreeDaysMerchant="<?php echo $block->getConfig()->getInterestFreeDay() ?>"
        data-c2-mode="<?php echo $block->getConfig()->getMode($block->getStoreId()) ? 'live' : 'test' ?>"
        data-c2-locale="<?php echo $block->getLocale() ?>"
        data-c2-email="<?php echo  $customer->getEmail() ?>"
        data-c2-given="<?php echo  $customer->getFirstname() ?>"
        data-c2-family="<?php echo  $customer->getLastname() ?>"
        data-c2-birthdate="<?php echo  $customer->getDob() ?>"
        data-c2-country="<?php echo  $customer->getCountryId() ?>"
        data-c2-city="<?php echo  $customer->getCity() ?>"
        data-c2-zip="<?php echo  $customer->getPostcode() ?>"
        data-c2-addressline="<?php echo  $customer->getStreet() ?>"
        data-c2-phone="<?php echo  $customer->getTelephone() ?>"
        data-c2-iban="<?php echo  $customer->getTaxvat() ?>"
        data-c2-amount="<?php echo $block->getGrandTotal() ?>">
</script>
