<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $config = $this->getCashpressoConfig(); ?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <div id="ls-checkout-success" style="display: none">
        <?php if ($block->getOrderId()):?>
            <?php if ($block->getCanViewOrder()) :?>
                <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
            <?php  else :?>
                <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
            <?php endif;?>
                <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
        <?php endif;?>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        require([
            'jquery',
        ], function($){
            if (!window.c2SuccessCallback) {
                window.c2SuccessCallback = function() {

                    $('#ls-checkout-success').css('display', 'block');

                    $('#ls_shopping_button').css('display', 'block');

                    $('.page-title .base').html("<?php echo $config->getSuccessTitle() ?>");

                    $('#ls_cashpresso_contract_text').html("<?php echo $config->getSuccessText() ?>");

                    $('.c2-btn-primary').html("<?php echo $config->getSuccessButtonTitle() ?>");
                }
            }
        });
        //]]>
    </script>

    <script id="c2PostCheckoutScript" type="text/javascript"
            src="<?php echo $config->getJsPostCheckoutScript() ?>"
            defer
            data-c2-partnerApiKey="<?php echo $config->getAPIKey() ?>"
            data-c2-purchaseId="<?php echo $this->getPurchaseId() ?>"
            data-c2-mode="<?php echo $config->getMode() ? 'live' : 'test' ?>"
            data-c2-locale="<?php echo $this->getLocale() ?>"
            data-c2-successCallback="true"
    ></script>

    <p id="ls_cashpresso_contract_text" style="margin-top:10px; align: center;"><?= $config->getContractText() ?></p>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar" id="ls_shopping_button" style="display: none;">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>